/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import DTO.UsuarioMasterDTO;
import Persistencia.Conexao;
import Persistencia.FuncProjeto;
import Persistencia.FuncRequisitos;
import Persistencia.FuncoesUsuariosBD;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author georg
 */
public class jfCadastroProjeto extends javax.swing.JFrame {
 
    static UsuarioMasterDTO usuario = new UsuarioMasterDTO();
    public jfCadastroProjeto(UsuarioMasterDTO usuario) {
        this.usuario = usuario;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtNome = new javax.swing.JTextField();
        jtUsuarioprop = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbInserir = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jtDescricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProjetosLista = new javax.swing.JTable();
        jbCarregarProjeto = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Projetos");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jtUsuarioprop.setEnabled(false);

        jLabel1.setText("Nome do Projeto");

        jLabel2.setText("Descricao");

        jLabel3.setText("Autor");

        jbInserir.setText("Adicionar Novo Projeto");
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jtProjetosLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Descricao", "Usuario Proprietario"
            }
        ));
        jScrollPane1.setViewportView(jtProjetosLista);
        if (jtProjetosLista.getColumnModel().getColumnCount() > 0) {
            jtProjetosLista.getColumnModel().getColumn(2).setPreferredWidth(600);
        }

        jbCarregarProjeto.setText("Carregar Projeto Selecionado");
        jbCarregarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarregarProjetoActionPerformed(evt);
            }
        });

        jbAtualizar.setText("Atualizar Info. do Projeto");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jtId.setEnabled(false);

        jLabel4.setText("ID do Projeto");

        jButton1.setText("Excluir Projeto Selecionado (Cuidado)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbInserir, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(jbSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbCarregarProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jtUsuarioprop, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8)
                        .addComponent(jtDescricao)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtUsuarioprop, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbCarregarProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed

   
        inserir();
        CarregarTabelaProj();
    }//GEN-LAST:event_jbInserirActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed

       atualizar();
       CarregarTabelaProj();
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jbCarregarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarregarProjetoActionPerformed
        carregarForm();
    }//GEN-LAST:event_jbCarregarProjetoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jtUsuarioprop.setText(usuario.getNome());
        CarregarTabelaProj();
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        deletarProejto();
        CarregarTabelaProj();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfCadastroProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfCadastroProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfCadastroProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfCadastroProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfCadastroProjeto(usuario).setVisible(true);
            }
        });
    }
    
      
     public void CarregarTabelaProj(){
         
            String sqlSelect = "select * from projetos";
            Conexao conexao = new Conexao();

            try(Connection conn = conexao.conectabd()){
                PreparedStatement stm = conn.prepareStatement(sqlSelect);
                ResultSet rs = stm.executeQuery();

                DefaultTableModel modelo = (DefaultTableModel) jtProjetosLista.getModel();
                modelo.setNumRows(0);


                while(rs.next()){

                    modelo.addRow(new Object[]{rs.getInt("id"),rs.getString("nome"),rs.getString("descricao"),rs.getString("usuarioprop")});
                    //int id = rs.getInt("id");               

                }
                rs.close();
                conn.close();
            }catch(SQLException e){
                e.printStackTrace();
            }
     }
     
     
     public void deletarProejto(){
         
            int setar = jtProjetosLista.getSelectedRow();

            try{String sqlSelect = "delete from projetos where id=?";
            Conexao conexao = new Conexao();

            FuncProjeto projetos = new FuncProjeto();
            projetos.setId((Integer)jtProjetosLista.getModel().getValueAt(setar,0));


                Connection conn = conexao.conectabd();
                PreparedStatement stm = conn.prepareStatement(sqlSelect);
                stm.setInt(1, projetos.getId() ); 
                stm.execute();
            }catch(Exception e){
                System.out.println("Eita");
            }


        }
     
        
        public void inserir(){
        try {
        String nome,descricao,usuarioprop ;
        
        
        nome = jtNome.getText();
        descricao = jtDescricao.getText();
        usuarioprop = jtUsuarioprop.getText();        

        
        FuncProjeto funcaousuario = new FuncProjeto();
            System.out.println("To parado aqui 1");
        funcaousuario.setNome(nome);
        funcaousuario.setDescricao(descricao);
        funcaousuario.setUsuarioprop(usuarioprop);


        
        funcaousuario.inserir();
        System.out.println("To parado aqui 4");
        jtDescricao.setText("");
        jtNome.setText("");
        jtUsuarioprop.setText("");
        
       

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro Botao"+e);
        }        
}
        
        
        public void atualizar(){
        
            String nome;
                String usuarioprop;
                String descricao;
                int id;
                
                               
                nome = jtNome.getText();
                usuarioprop = jtUsuarioprop.getText();
                descricao = jtDescricao.getText();
                id = Integer.parseInt(jtId.getText());

                
                
                
                
                FuncProjeto projeto = new FuncProjeto();
                
                projeto.setNome(nome);
                projeto.setUsuarioprop(usuarioprop);
                projeto.setDescricao(descricao);
                projeto.setId(id);


                

                String sqlInsert = "update projetos set nome = ?, descricao = ?,usuarioprop = ? where id = ?";
                Conexao conexao = new Conexao();
                System.out.println("To parado aqui 3");
                try(Connection conn = conexao.conectabd()){
                    PreparedStatement stm = conn.prepareStatement(sqlInsert);

                    stm.setString(1, projeto.getNome());
                    stm.setString(2, projeto.getDescricao());
                    stm.setString(3, projeto.getUsuarioprop());
                    stm.setInt(4, projeto.getId());
                    stm.execute();
                CarregarTabelaProj();
                }catch(SQLException e){
                    e.printStackTrace();
                }
            }
        
        
        public void carregarForm(){
                int setar = jtProjetosLista.getSelectedRow();
                jtId.setText(jtProjetosLista.getModel().getValueAt(setar,0).toString());
                jtNome.setText(jtProjetosLista.getModel().getValueAt(setar,1).toString());
                jtDescricao.setText(jtProjetosLista.getModel().getValueAt(setar,2).toString());
                jtUsuarioprop.setText(jtProjetosLista.getModel().getValueAt(setar,3).toString());
        }
        
     
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbCarregarProjeto;
    private javax.swing.JButton jbInserir;
    private javax.swing.JButton jbSair;
    private javax.swing.JTextField jtDescricao;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTable jtProjetosLista;
    private javax.swing.JTextField jtUsuarioprop;
    // End of variables declaration//GEN-END:variables
}
