/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Persistencia.Conexao;
import Persistencia.FuncRequisitos;
import Persistencia.FuncoesUsuariosBD;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author georg
 */
public class jfCadastro extends javax.swing.JFrame {

    static int master;
    public jfCadastro(int master) {
        this.master = master;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtEmail = new javax.swing.JTextField();
        jtTel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbSair = new javax.swing.JButton();
        jbCadastrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtSenha = new javax.swing.JTextField();
        jbAtualizar = new javax.swing.JButton();
        jbCarregarForm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtUsuarios = new javax.swing.JTable();
        jbExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtID = new javax.swing.JTextField();
        jtMaster = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Projeto");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Usuario");

        jLabel2.setText("Nome Completo");

        jLabel6.setText("Telefone:");

        jLabel4.setText("Email");

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jbCadastrar.setText("Criar Novo");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Senha");

        jbAtualizar.setText("Atualizar Info. do Usuario");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jbCarregarForm.setText("Carregar Usuario Selecionado para Formulario");
        jbCarregarForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarregarFormActionPerformed(evt);
            }
        });

        jtUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome Completo", "Email", "Telefone", "Usuario", "Senha", "Autorizacao"
            }
        ));
        jScrollPane1.setViewportView(jtUsuarios);
        if (jtUsuarios.getColumnModel().getColumnCount() > 0) {
            jtUsuarios.getColumnModel().getColumn(1).setPreferredWidth(350);
            jtUsuarios.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        jbExcluir.setText("Excluir Usuario Selecionado (Cuidado)");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jLabel5.setText("ID Usuario");

        jtID.setEnabled(false);

        jtMaster.setEnabled(false);

        jLabel7.setText("Autorizacao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3)
                                                .addGap(130, 130, 130))
                                            .addComponent(jLabel4)
                                            .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtID)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jtMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(94, 94, 94)
                                        .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbCarregarForm)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1773, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel2)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCarregarForm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtID)
                                    .addComponent(jtMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed

        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        criar();
        carregarTabelaUsuarios();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbCarregarFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarregarFormActionPerformed
            carregarForm();
    }//GEN-LAST:event_jbCarregarFormActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

            carregarTabelaUsuarios();
    }//GEN-LAST:event_formWindowActivated

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
          atualizar();
          carregarTabelaUsuarios();
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        deletarUsuario();
        carregarTabelaUsuarios();
    }//GEN-LAST:event_jbExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfCadastro(master).setVisible(true);
            }
        });
    }
        
    
    
        public void carregarTabelaUsuarios(){
        String sqlSelect = "select * from usuarios";
        Conexao conexao = new Conexao();

        try(Connection conn = conexao.conectabd()){
            PreparedStatement stm = conn.prepareStatement(sqlSelect);
            ResultSet rs = stm.executeQuery();
            
            DefaultTableModel modelo = (DefaultTableModel) jtUsuarios.getModel();
            modelo.setNumRows(0);
            
            
            while(rs.next()){
                
                modelo.addRow(new Object[]{rs.getInt("id"),rs.getString("nome"),rs.getString("email"),rs.getString("fone"),rs.getString("login"),rs.getString("senha"),rs.getString("master")});
                //int id = rs.getInt("id");               
                
            }
            rs.close();
            conn.close();
        }catch(SQLException e){
            e.printStackTrace();
        }
        }
        
        
        
        public void carregarForm(){
        int setar = jtUsuarios.getSelectedRow();
        jtID.setText(jtUsuarios.getModel().getValueAt(setar,0).toString());
//        int setar = jtRequisitos.getSelectedRow();


        try{String sqlSelect = "select * from usuarios where id=?";
        Conexao conexao = new Conexao();
        
        FuncoesUsuariosBD usuarios = new FuncoesUsuariosBD();

      
                
            Connection conn = conexao.conectabd();
            PreparedStatement stm = conn.prepareStatement(sqlSelect);
            stm.setString(1, jtUsuarios.getModel().getValueAt(setar,0).toString());
            ResultSet rs = stm.executeQuery();
//            java.sql.Date sqldate = new java.sql.Date(jdDatacriacao.getDate().getTime());
//            java.sql.Date sqldate1 = new java.sql.Date(jdDataAlteracao.getDate().getTime());
//            
//            DefaultTableModel modelo1 = (DefaultTableModel) jtRequisitos.getModel();
//            modelo1.setNumRows(0);
            while(rs.next()){

                jtNome.setText(rs.getString("nome"));
                jtID.setText(rs.getString("id"));
                jtEmail.setText(rs.getString("email"));
                jtTel.setText(rs.getString("fone"));
                jtUsuario.setText(rs.getString("login"));
                jtSenha.setText(rs.getString("senha"));
                jtMaster.setText(rs.getString("master"));




            }
            rs.close();
            conn.close();

        }catch(SQLException e){
            e.printStackTrace();
        }
        
        }
        public void deletarUsuario(){
        int setar = jtUsuarios.getSelectedRow();
        int id =((Integer)jtUsuarios.getModel().getValueAt(setar,0));
        try{String sqlSelect = "delete from usuarios where id=?";
        Conexao conexao = new Conexao();
        
            FuncoesUsuariosBD usuarios = new FuncoesUsuariosBD();
            usuarios.setId(id);
      
                
            Connection conn = conexao.conectabd();
            PreparedStatement stm = conn.prepareStatement(sqlSelect);
            stm.setInt(1, usuarios.getId() ); 
            stm.execute();
        }catch(Exception e){
            System.out.println("Eita");
        }
            
            
        }
        
        public void atualizar(){


            
                String nome;
                String email;
                String fone;
                String login;
                String senha;
                int id;
                       
                nome = jtNome.getText();
                email = jtEmail.getText();
                fone = jtTel.getText();
                login = jtUsuario.getText();
                senha = jtSenha.getText();
                id = Integer.parseInt(jtID.getText());

             
                FuncoesUsuariosBD usuarios = new FuncoesUsuariosBD();
                
                usuarios.setNome(nome);
                usuarios.setEmail(email);
                usuarios.setFone(fone);
                usuarios.setLogin(login);
                usuarios.setSenha(senha);
                usuarios.setId(id);

           

                String sqlInsert = "update usuarios set nome = ?, email = ?,fone = ?, login = ?, senha = ? where id = ?";
                Conexao conexao = new Conexao();
                System.out.println("To parado aqui 3");
                try(Connection conn = conexao.conectabd()){
                    PreparedStatement stm = conn.prepareStatement(sqlInsert);

                    stm.setString(1, usuarios.getNome());
                    stm.setString(2, usuarios.getEmail());
                    stm.setString(3, usuarios.getFone());
                    stm.setString(4, usuarios.getLogin());
                    stm.setString(5, usuarios.getSenha());
                    stm.setInt(6, usuarios.getId());
                    

                    stm.execute();
                    
                    jtEmail.setText("");
                    jtNome.setText("");
                    jtSenha.setText("");
                    jtTel.setText("");
                    jtUsuario.setText("");
                    jtMaster.setText("");
                    jtID.setText("");
                }catch(SQLException e){
                    e.printStackTrace();
                }      
        }
        
        
        public void criar(){
        try{
        String nome,email,fone,login,senha ;
        
        
        nome = jtNome.getText();
        email = jtEmail.getText();
        fone = jtTel.getText();        
        login = jtUsuario.getText();
        senha = jtSenha.getText();
        int master;
        
        FuncoesUsuariosBD funcaousuario = new FuncoesUsuariosBD();
        
        funcaousuario.setNome(nome);
        funcaousuario.setEmail(email);
        funcaousuario.setFone(fone);
        funcaousuario.setLogin(login);
        funcaousuario.setSenha(senha);

        
        funcaousuario.inserir();
        carregarTabelaUsuarios();
        jtEmail.setText("");
        jtNome.setText("");
        jtSenha.setText("");
        jtTel.setText("");
        jtUsuario.setText("");
        
       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro Botao"+e);
        }


        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbCarregarForm;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbSair;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtID;
    private javax.swing.JTextField jtMaster;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtSenha;
    private javax.swing.JTextField jtTel;
    private javax.swing.JTextField jtUsuario;
    private javax.swing.JTable jtUsuarios;
    // End of variables declaration//GEN-END:variables
}
