/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Persistencia.Conexao;
import Persistencia.FuncRequisitos;
import Persistencia.FuncoesUsuariosBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author georg
 */
public class jfListaProj extends javax.swing.JFrame {

    /**
     * Creates new form jfListaProj
     */
    public jfListaProj() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtUsuarios = new javax.swing.JTable();
        jtPesquisa = new javax.swing.JTextField();
        btPesquisa = new javax.swing.JButton();
        btListar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcAtributo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jtUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome do Projeto", "Usuario Proprietario", "Descricao"
            }
        ));
        jScrollPane1.setViewportView(jtUsuarios);
        if (jtUsuarios.getColumnModel().getColumnCount() > 0) {
            jtUsuarios.getColumnModel().getColumn(3).setPreferredWidth(600);
        }

        btPesquisa.setText("Pesquisa");
        btPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaActionPerformed(evt);
            }
        });

        btListar.setText("Listar Todos");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });

        jLabel1.setText("Caixa de Pesquisa");

        jcAtributo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcAtributo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id", "nome", "descricao", "usuarioprop" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jcAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btPesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(btListar)))
                .addContainerGap(1311, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btListar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaActionPerformed
        pesquisarPorAtributo();
    }//GEN-LAST:event_btPesquisaActionPerformed

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
        carregarLista();
    }//GEN-LAST:event_btListarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfListaProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfListaProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfListaProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfListaProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfListaProj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btListar;
    private javax.swing.JButton btPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcAtributo;
    private javax.swing.JTextField jtPesquisa;
    private javax.swing.JTable jtUsuarios;
    // End of variables declaration//GEN-END:variables
public void pesquisarPorAtributo(){
//        int setar = jtUsuarios.getSelectedRow();
//        jtID.setText(jtUsuarios.getModel().getValueAt(setar,0).toString());
//        int setar = jtRequisitos.getSelectedRow();

        String atributo = jcAtributo.getSelectedItem().toString();
        try{String sqlSelect = "select * from projetos where "+atributo+" = ?";
        Conexao conexao = new Conexao();
        
//            FuncRequisitos requisitos = new FuncRequisitos();


            System.out.println(atributo);
            System.out.println(jtPesquisa.getText());
            
            Connection conn = conexao.conectabd();
            PreparedStatement stm = conn.prepareStatement(sqlSelect);
//            stm.setString(1, atributo);
//            stm.setString(1, '%'+jtPesquisa.getText()+'%');
            stm.setString(1,jtPesquisa.getText());
            System.out.println(stm.toString());
            ResultSet rs = stm.executeQuery();
//            java.sql.Date sqldate = new java.sql.Date(jdDatacriacao.getDate().getTime());
//            java.sql.Date sqldate1 = new java.sql.Date(jdDataAlteracao.getDate().getTime());
            DefaultTableModel modelo = (DefaultTableModel) jtUsuarios.getModel();
            modelo.setNumRows(0);
//            DefaultTableModel modelo1 = (DefaultTableModel) jtRequisitos.getModel();
//            modelo1.setNumRows(0);
            while(rs.next()){

//                jtNome.setText(rs.getString("nome"));
//                jtID.setText(rs.getString("id"));
//                jtEmail.setText(rs.getString("email"));
//                jtTel.setText(rs.getString("fone"));
//                jtUsuario.setText(rs.getString("login"));
//                jtSenha.setText(rs.getString("senha"));
//                jtMaster.setText(rs.getString("master"));
                modelo.addRow(new Object[]{rs.getInt("id"),rs.getString("nome"),rs.getString("descricao"),rs.getString("usuarioprop")});



            }
            rs.close();
            conn.close();

        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    public void carregarLista(){
//        int setar = jtUsuarios.getSelectedRow();
//        jtID.setText(jtUsuarios.getModel().getValueAt(setar,0).toString());
//        int setar = jtRequisitos.getSelectedRow();


        try{String sqlSelect = "select * from projetos";
        Conexao conexao = new Conexao();
        
//        FuncoesUsuariosBD usuarios = new FuncoesUsuariosBD();

      
                
            Connection conn = conexao.conectabd();
            PreparedStatement stm = conn.prepareStatement(sqlSelect);
//            stm.setString(1, jtUsuarios.getModel().getValueAt(setar,0).toString());
            ResultSet rs = stm.executeQuery();
//            java.sql.Date sqldate = new java.sql.Date(jdDatacriacao.getDate().getTime());
//            java.sql.Date sqldate1 = new java.sql.Date(jdDataAlteracao.getDate().getTime());
            DefaultTableModel modelo = (DefaultTableModel) jtUsuarios.getModel();
            modelo.setNumRows(0);
//            DefaultTableModel modelo1 = (DefaultTableModel) jtRequisitos.getModel();
//            modelo1.setNumRows(0);
            while(rs.next()){

//                jtNome.setText(rs.getString("nome"));
//                jtID.setText(rs.getString("id"));
//                jtEmail.setText(rs.getString("email"));
//                jtTel.setText(rs.getString("fone"));
//                jtUsuario.setText(rs.getString("login"));
//                jtSenha.setText(rs.getString("senha"));
//                jtMaster.setText(rs.getString("master"));
                modelo.addRow(new Object[]{rs.getInt("id"),rs.getString("nome"),rs.getString("descricao"),rs.getString("usuarioprop")});



            }
            rs.close();
            conn.close();

        }catch(SQLException e){
            e.printStackTrace();
        }
    }


}