/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import DTO.UsuarioMasterDTO;

/**
 *
 * @author georg
 */
public class jfprincipal extends javax.swing.JFrame {
    

    static UsuarioMasterDTO usuario = new UsuarioMasterDTO();
    
    
    public jfprincipal(UsuarioMasterDTO usuario) {
        this.usuario = usuario;
        System.out.println("\n"+usuario.getMaster());
        int master = usuario.getMaster();
        
        initComponents();
       
        
    }
    public void desabilitarBotao(UsuarioMasterDTO usuario){
        jfprincipal.usuario = usuario;
        System.out.println("master "+usuario.getMaster());
        if(usuario.getMaster()==1){
            jmCadastroProjeto.setEnabled(true);
            jmCadastroRequisitos.setEnabled(true);
            jmCadastroUsuario.setEnabled(true);
            jmListaProj.setEnabled(true);
            jmListaReq.setEnabled(true);
            jmListaUser.setEnabled(true);

            
        }else if(usuario.getMaster()==0){
            jmListaProj.setEnabled(true);
            jmListaReq.setEnabled(true); 
            jmCadastroRequisitos.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmLogin = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmListaProj = new javax.swing.JMenuItem();
        jmListaReq = new javax.swing.JMenuItem();
        jmListaUser = new javax.swing.JMenuItem();
        jmCadastro = new javax.swing.JMenu();
        jmCadastroProjeto = new javax.swing.JMenuItem();
        jmCadastroRequisitos = new javax.swing.JMenuItem();
        jmCadastroUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ReqEasytos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1929, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );

        jMenu1.setText("Login");

        jmLogin.setText("Login");
        jmLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLoginActionPerformed(evt);
            }
        });
        jMenu1.add(jmLogin);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Listagem");

        jmListaProj.setText("Projetos");
        jmListaProj.setEnabled(false);
        jmListaProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListaProjActionPerformed(evt);
            }
        });
        jMenu2.add(jmListaProj);

        jmListaReq.setText("Requisitos");
        jmListaReq.setEnabled(false);
        jmListaReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListaReqActionPerformed(evt);
            }
        });
        jMenu2.add(jmListaReq);

        jmListaUser.setText("Usuarios");
        jmListaUser.setEnabled(false);
        jmListaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListaUserActionPerformed(evt);
            }
        });
        jMenu2.add(jmListaUser);

        jMenuBar1.add(jMenu2);

        jmCadastro.setText("CRUD");
        jmCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroActionPerformed(evt);
            }
        });

        jmCadastroProjeto.setText("Projetos");
        jmCadastroProjeto.setEnabled(false);
        jmCadastroProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroProjetoActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadastroProjeto);

        jmCadastroRequisitos.setText("Requisitos");
        jmCadastroRequisitos.setEnabled(false);
        jmCadastroRequisitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroRequisitosActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadastroRequisitos);

        jmCadastroUsuario.setText("Usuarios");
        jmCadastroUsuario.setEnabled(false);
        jmCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroUsuarioActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadastroUsuario);

        jMenuBar1.add(jmCadastro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);


        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jmCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jmCadastroActionPerformed

    private void jmCadastroProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroProjetoActionPerformed
       
        jfCadastroProjeto obj = new jfCadastroProjeto(usuario);       
        obj.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jmCadastroProjetoActionPerformed

    private void jmLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLoginActionPerformed
        //if(login==false){
        new jfLogin().setVisible(true);

        //}
        // TODO add your handling code here:
    }//GEN-LAST:event_jmLoginActionPerformed

    private void jmListaReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListaReqActionPerformed
        new jfListaReq().setVisible(true);
    }//GEN-LAST:event_jmListaReqActionPerformed

    private void jmCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroUsuarioActionPerformed
        jfCadastro obj = new jfCadastro(usuario.getMaster());
        obj.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jmCadastroUsuarioActionPerformed

    private void jmListaProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListaProjActionPerformed
        new jfListaProj().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jmListaProjActionPerformed

    private void jmListaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListaUserActionPerformed
        jfListaUser obj = new jfListaUser();
        obj.setVisible(true);
    }//GEN-LAST:event_jmListaUserActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        
        desabilitarBotao(usuario);   
           
          
        
    }//GEN-LAST:event_formWindowActivated

    private void jmCadastroRequisitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroRequisitosActionPerformed
        jfRequisitos obj = new jfRequisitos(usuario);
        obj.setVisible(true);
    }//GEN-LAST:event_jmCadastroRequisitosActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfprincipal(usuario).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenuItem jmCadastroProjeto;
    private javax.swing.JMenuItem jmCadastroRequisitos;
    private javax.swing.JMenuItem jmCadastroUsuario;
    private javax.swing.JMenuItem jmListaProj;
    private javax.swing.JMenuItem jmListaReq;
    private javax.swing.JMenuItem jmListaUser;
    private javax.swing.JMenuItem jmLogin;
    // End of variables declaration//GEN-END:variables




}
