/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Persistencia.Conexao;
import Persistencia.FuncProjeto;
import Persistencia.FuncRequisitos;
import Persistencia.FuncoesUsuariosBD;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author georg
 */
public class jfRequisitos extends javax.swing.JFrame {

    /**
     * Creates new form jfRequisitos
     */
    public jfRequisitos() {
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtNome = new javax.swing.JTextField();
        jtUsuarioprop = new javax.swing.JTextField();
        jtModulo = new javax.swing.JTextField();
        jtFuncionalidades = new javax.swing.JTextField();
        jtAutor = new javax.swing.JTextField();
        jtVersao = new javax.swing.JTextField();
        jtAutoralteracao = new javax.swing.JTextField();
        jtPrioridade = new javax.swing.JTextField();
        jtComplexidade = new javax.swing.JTextField();
        jtEsforcohoras = new javax.swing.JTextField();
        jtFase = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jdDatacriacao = new com.toedter.calendar.JDateChooser();
        jdDataAlteracao = new com.toedter.calendar.JDateChooser();
        jbConsultarRequisitos = new javax.swing.JButton();
        jbAdicionar = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jtNomeProjeto = new javax.swing.JTextField();
        jtEstado = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtRequisitos = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtProjetos = new javax.swing.JTable();
        jbCarregarNomeProjeto = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtpDescricao = new javax.swing.JTextPane();
        jbCarregarForm = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jtID = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Requisitos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeActionPerformed(evt);
            }
        });

        jtPrioridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPrioridadeActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario Proprietario");

        jLabel2.setText("Nome");

        jLabel3.setText("Modulo");

        jLabel4.setText("Funcionalidades");

        jLabel5.setText("Data de criacao");

        jLabel6.setText("Autor");

        jLabel7.setText("Data da ultima Alteracao");

        jLabel8.setText("Autor da ultima alteracao");

        jLabel9.setText("Versao");

        jLabel10.setText("Prioridade");

        jLabel11.setText("Complexidade");

        jLabel12.setText("Esforco estimado em horas");

        jLabel13.setText("Estado");

        jLabel14.setText("Fase");

        jLabel15.setText("Descricao");

        jbConsultarRequisitos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbConsultarRequisitos.setText("Carregar Tabela de Requisitos");
        jbConsultarRequisitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarRequisitosActionPerformed(evt);
            }
        });

        jbAdicionar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbAdicionar.setText("Criar Novo");
        jbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarActionPerformed(evt);
            }
        });

        jbSair.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jLabel16.setText("Nome do Projeto");

        jtNomeProjeto.setEnabled(false);

        jtRequisitos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome Req.", "Modulo", "Descricao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtRequisitos);
        if (jtRequisitos.getColumnModel().getColumnCount() > 0) {
            jtRequisitos.getColumnModel().getColumn(0).setResizable(false);
            jtRequisitos.getColumnModel().getColumn(0).setPreferredWidth(25);
            jtRequisitos.getColumnModel().getColumn(1).setResizable(false);
            jtRequisitos.getColumnModel().getColumn(2).setResizable(false);
            jtRequisitos.getColumnModel().getColumn(3).setResizable(false);
            jtRequisitos.getColumnModel().getColumn(3).setPreferredWidth(600);
        }

        jtProjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID do Projeto", "Nome do Projeto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jtProjetos);

        jbCarregarNomeProjeto.setText("Carregar Nome do Projeto Selecionado");
        jbCarregarNomeProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarregarNomeProjetoActionPerformed(evt);
            }
        });

        jbAtualizar.setText("Atualizar Info. do Requisito");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jtpDescricao);

        jbCarregarForm.setText("Carregar Requisito Selecionado para Formulario");
        jbCarregarForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarregarFormActionPerformed(evt);
            }
        });

        jButton4.setText("Excluir Requisito Selecionado (Cuidado)");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jtID.setEnabled(false);

        jLabel17.setText("ID do Requisito");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtNomeProjeto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtAutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addComponent(jtFuncionalidades, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addComponent(jtModulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addComponent(jtNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtVersao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jdDatacriacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtUsuarioprop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addComponent(jLabel16)
                    .addComponent(jtID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbCarregarNomeProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbConsultarRequisitos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbCarregarForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jbAtualizar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jtComplexidade, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtAutoralteracao, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(jtEsforcohoras, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addComponent(jdDataAlteracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addComponent(jtFase, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addComponent(jtEstado))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jtPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtComplexidade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jtEsforcohoras, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addGap(6, 6, 6)
                                .addComponent(jtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(16, 16, 16)
                                .addComponent(jtFase, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbConsultarRequisitos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbCarregarForm, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbCarregarNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdDataAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtUsuarioprop, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtAutoralteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtFuncionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jdDatacriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jtNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(424, 424, 424)
                                        .addComponent(jScrollPane2)))
                                .addContainerGap())))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtPrioridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPrioridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPrioridadeActionPerformed

    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed
        criar();
        CarregarTabelaRequisitos();
    }//GEN-LAST:event_jbAdicionarActionPerformed

    private void jtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeActionPerformed

    private void jbConsultarRequisitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarRequisitosActionPerformed

        CarregarTabelaRequisitos();
    }//GEN-LAST:event_jbConsultarRequisitosActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        carregarProjeto();
    
    }//GEN-LAST:event_formWindowActivated

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbCarregarNomeProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarregarNomeProjetoActionPerformed
        
        int setar = jtProjetos.getSelectedRow();
        jtNomeProjeto.setText(jtProjetos.getModel().getValueAt(setar,1).toString());
    }//GEN-LAST:event_jbCarregarNomeProjetoActionPerformed

    private void jbCarregarFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarregarFormActionPerformed

            PreencherForm();
    }//GEN-LAST:event_jbCarregarFormActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
                atualizar();
                CarregarTabelaRequisitos();
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        deletarRequisito();
        CarregarTabelaRequisitos();
    }//GEN-LAST:event_jButton4ActionPerformed
        public void carregarProjeto(){
                    
        String sqlSelect = "select * from projetos";
        Conexao conexao = new Conexao();

        try(Connection conn = conexao.conectabd()){
            PreparedStatement stm = conn.prepareStatement(sqlSelect);
            ResultSet rs = stm.executeQuery();
            
            DefaultTableModel modelo = (DefaultTableModel) jtProjetos.getModel();
            modelo.setNumRows(0);
            
            
            while(rs.next()){
                
                modelo.addRow(new Object[]{rs.getInt("id"),rs.getString("nome")});
                //int id = rs.getInt("id");               
                
            }
            rs.close();
            conn.close();
        }catch(SQLException e){
            e.printStackTrace();
        }

        }
    
    
    
    
    
    
      public void CarregarTabelaRequisitos(){
      try{ String nomeprojeto;
//    
      nomeprojeto = jtNomeProjeto.getText();

//    FuncRequisitos requisitos = new FuncRequisitos();
//    

//    
//    requisitos.consultarVisual();
//    
//    }catch(Exception e){
//        System.out.println("Deu buesta");
//    }
        String sqlSelect = "select * from requisitos where nomeprojeto=?";
        Conexao conexao = new Conexao();
        
        FuncRequisitos requisitos = new FuncRequisitos();
        requisitos.setNomeprojeto(nomeprojeto);
               
                
            Connection conn = conexao.conectabd();
            PreparedStatement stm = conn.prepareStatement(sqlSelect);
            stm.setString(1, requisitos.getNomeprojeto());
            ResultSet rs = stm.executeQuery();
            
            DefaultTableModel modelo1 = (DefaultTableModel) jtRequisitos.getModel();
            modelo1.setNumRows(0);
            while(rs.next()){
                modelo1.addRow(new Object[]{rs.getInt("ididentificador"),rs.getString("nome"),rs.getString("modulo"),rs.getString("descricao")});
                
            }
            rs.close();
            conn.close();

        }catch(SQLException e){
            e.printStackTrace();
        }
    
      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfRequisitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfRequisitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfRequisitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfRequisitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfRequisitos().setVisible(true);
            }
        });
    }

        public void PreencherForm(){
        int setar = jtRequisitos.getSelectedRow();
        jtID.setText(jtRequisitos.getModel().getValueAt(setar,0).toString());
//        int setar = jtRequisitos.getSelectedRow();


        try{String sqlSelect = "select * from requisitos where ididentificador=?";
        Conexao conexao = new Conexao();
        
        FuncRequisitos requisitos = new FuncRequisitos();

      
                
            Connection conn = conexao.conectabd();
            PreparedStatement stm = conn.prepareStatement(sqlSelect);
            stm.setString(1, jtRequisitos.getModel().getValueAt(setar,0).toString());
            ResultSet rs = stm.executeQuery();
//            java.sql.Date sqldate = new java.sql.Date(jdDatacriacao.getDate().getTime());
//            java.sql.Date sqldate1 = new java.sql.Date(jdDataAlteracao.getDate().getTime());
//            
//            DefaultTableModel modelo1 = (DefaultTableModel) jtRequisitos.getModel();
//            modelo1.setNumRows(0);
            while(rs.next()){

                jtNome.setText(rs.getString("nome"));
                jtUsuarioprop.setText(rs.getString("usuarioprop"));
                jtModulo.setText(rs.getString("modulo"));
                jtFuncionalidades.setText(rs.getString("funcionalidade"));
                jdDatacriacao.setDate(rs.getDate("datacriacao"));
                jtAutor.setText(rs.getString("autor"));
                jdDataAlteracao.setDate(rs.getDate("dataultimaalter"));
                jtAutoralteracao.setText(rs.getString("autorultimaalter"));
                jtVersao.setText(rs.getString("versao"));
                jtPrioridade.setText(rs.getString("prioridade"));
                jtComplexidade.setText(rs.getString("complexidade"));
                jtEsforcohoras.setText(rs.getString("esforcohoras"));
                jtEstado.setText(rs.getString("estado"));
                jtFase.setText(rs.getString("fase"));
                jtpDescricao.setText(rs.getString("descricao"));



            }
            rs.close();
            conn.close();

        }catch(SQLException e){
            e.printStackTrace();
        }
        }
        
        public void deletarRequisito(){
        int setar = jtRequisitos.getSelectedRow();
        int ididentificador =((Integer)jtRequisitos.getModel().getValueAt(setar,0));
        try{String sqlSelect = "delete from requisitos where ididentificador=?";
        Conexao conexao = new Conexao();
        
        FuncRequisitos requisitos = new FuncRequisitos();
        requisitos.setIdidentificador(ididentificador);
      
                
            Connection conn = conexao.conectabd();
            PreparedStatement stm = conn.prepareStatement(sqlSelect);
            stm.setInt(1, requisitos.getIdidentificador() ); 
            stm.execute();
        }catch(Exception e){
            System.out.println("Eita");
        }
            
            
        }
        
        public void atualizar(){
                int setar = jtRequisitos.getSelectedRow();

                String nome;
                String usuarioprop;
                String modulo;
                String funcionalidade;
                Date datacriacao;
                String autor;
                Date dataultimaalteracao;
                String autorultimaalteracao;
                String versao;
                String prioridade;
                String complexidade;
                String esforcohoras;
                String estado;
                String fase;
                String descricao;
                String nomeprojeto;
                int ididentificador;
                
                java.sql.Date sqldate = new java.sql.Date(jdDatacriacao.getDate().getTime());
                java.sql.Date sqldate1 = new java.sql.Date(jdDataAlteracao.getDate().getTime());
                
                nome = jtNome.getText();
                usuarioprop = jtUsuarioprop.getText();
                modulo = jtModulo.getText();
                funcionalidade = jtFuncionalidades.getText();
                datacriacao = sqldate;
                autor = jtUsuarioprop.getText();
                dataultimaalteracao = sqldate1;
                autorultimaalteracao = jtAutoralteracao.getText();
                versao = jtVersao.getText();
                prioridade = jtPrioridade.getText();
                complexidade = jtComplexidade.getText();
                esforcohoras = jtEsforcohoras.getText();
                estado = jtEstado.getText();
                fase = jtFase.getText();
                descricao = jtpDescricao.getText();
                nomeprojeto = jtNomeProjeto.getText();
                ididentificador = Integer.parseInt(jtID.getText());
                
                
                
                FuncRequisitos requisitos = new FuncRequisitos();
                
                requisitos.setNome(nome);
                requisitos.setUsuarioprop(usuarioprop);
                requisitos.setModulo(modulo);
                requisitos.setFuncionalidade(funcionalidade);
                requisitos.setDatacriacao(datacriacao);
                requisitos.setAutor(autor);
                requisitos.setDataultimaalteracao(dataultimaalteracao);
                requisitos.setAutorultimaalteracao(autorultimaalteracao);
                requisitos.setVersao(versao);
                requisitos.setPrioridade(prioridade);
                requisitos.setComplexidade(complexidade);
                requisitos.setEsforcohoras(esforcohoras);
                requisitos.setEstado(estado);
                requisitos.setFase(fase);
                requisitos.setDescricao(descricao);
                requisitos.setIdidentificador(ididentificador);
        
        
                            

                String sqlInsert = "update requisitos set nome = ?, descricao = ?,usuarioprop = ?, autor = ?, datacriacao = ?, modulo = ?, fase = ?,estado = ?,esforcohoras = ?,complexidade = ?,prioridade = ?,versao = ?,autorultimaalter = ?,dataultimaalter = ?, funcionalidade = ? where ididentificador = ?";
                Conexao conexao = new Conexao();
                System.out.println("To parado aqui 3");
                try(Connection conn = conexao.conectabd()){
                    PreparedStatement stm = conn.prepareStatement(sqlInsert);

                    stm.setString(1, requisitos.getNome());
                    stm.setString(2, requisitos.getDescricao());
                    stm.setString(3, requisitos.getUsuarioprop());
                    stm.setString(4, requisitos.getAutor());
                    stm.setDate(5, requisitos.getDatacriacao());
                    stm.setString(6, requisitos.getModulo());
                    stm.setString(7, requisitos.getFase());
                    stm.setString(8, requisitos.getEstado());
                    stm.setString(9, requisitos.getEsforcohoras());
                    stm.setString(10, requisitos.getComplexidade());
                    stm.setString(11, requisitos.getPrioridade());
                    stm.setString(12, requisitos.getVersao());
                    stm.setString(13, requisitos.getAutorultimaalteracao());
                    stm.setDate(14, requisitos.getDataultimaalteracao());
                    stm.setString(15, requisitos.getFuncionalidade());
                    stm.setInt(16, requisitos.getIdidentificador());                    

                    stm.execute();
                    CarregarTabelaRequisitos();
                }catch(SQLException e){
                    e.printStackTrace();
                  
                }
                
}
        
        public void criar(){
            int setar = jtProjetos.getSelectedRow();
        if(jtProjetos.getModel().getValueAt(setar,1).equals(jtNomeProjeto.getText())) {
            try{
                String nome;
                String usuarioprop;
                String modulo;
                String funcionalidade;
                Date datacriacao;
                String autor;
                Date dataultimaalteracao;
                String autorultimaalteracao;
                String versao;
                String prioridade;
                String complexidade;
                String esforcohoras;
                String estado;
                String fase;
                String descricao;
                String nomeprojeto;
                
                
                java.sql.Date sqldate = new java.sql.Date(jdDatacriacao.getDate().getTime());
                java.sql.Date sqldate1 = new java.sql.Date(jdDataAlteracao.getDate().getTime());
                
                nome = jtNome.getText();
                usuarioprop = jtUsuarioprop.getText();
                modulo = jtModulo.getText();
                funcionalidade = jtFuncionalidades.getText();
                datacriacao = sqldate;
                autor = jtUsuarioprop.getText();
                dataultimaalteracao = sqldate1;
                autorultimaalteracao = jtAutoralteracao.getText();
                versao = jtVersao.getText();
                prioridade = jtPrioridade.getText();
                complexidade = jtComplexidade.getText();
                esforcohoras = jtEsforcohoras.getText();
                estado = jtEstado.getText();
                fase = jtFase.getText();
                descricao = jtpDescricao.getText();
                nomeprojeto = jtNomeProjeto.getText();
                
                
                
                
                FuncRequisitos requisitos = new FuncRequisitos();
                
                requisitos.setNome(nome);
                requisitos.setUsuarioprop(usuarioprop);
                requisitos.setModulo(modulo);
                requisitos.setFuncionalidade(funcionalidade);
                requisitos.setDatacriacao(datacriacao);
                requisitos.setAutor(autor);
                requisitos.setDataultimaalteracao(dataultimaalteracao);
                requisitos.setAutorultimaalteracao(autorultimaalteracao);
                requisitos.setVersao(versao);
                requisitos.setPrioridade(prioridade);
                requisitos.setComplexidade(complexidade);
                requisitos.setEsforcohoras(esforcohoras);
                requisitos.setEstado(estado);
                requisitos.setFase(fase);
                requisitos.setDescricao(descricao);
                requisitos.setNomeprojeto(nomeprojeto);
                
                requisitos.inserir();
                
                
                
                
            }catch(Exception e){
                e.printStackTrace();
            }
        }else{
            System.out.println("Deu ruim!");
        }
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbCarregarForm;
    private javax.swing.JButton jbCarregarNomeProjeto;
    private javax.swing.JButton jbConsultarRequisitos;
    private javax.swing.JButton jbSair;
    private com.toedter.calendar.JDateChooser jdDataAlteracao;
    private com.toedter.calendar.JDateChooser jdDatacriacao;
    private javax.swing.JTextField jtAutor;
    private javax.swing.JTextField jtAutoralteracao;
    private javax.swing.JTextField jtComplexidade;
    private javax.swing.JTextField jtEsforcohoras;
    private javax.swing.JTextField jtEstado;
    private javax.swing.JTextField jtFase;
    private javax.swing.JTextField jtFuncionalidades;
    private javax.swing.JTextField jtID;
    private javax.swing.JTextField jtModulo;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNomeProjeto;
    private javax.swing.JTextField jtPrioridade;
    private javax.swing.JTable jtProjetos;
    private javax.swing.JTable jtRequisitos;
    private javax.swing.JTextField jtUsuarioprop;
    private javax.swing.JTextField jtVersao;
    private javax.swing.JTextPane jtpDescricao;
    // End of variables declaration//GEN-END:variables
}
